#!/bin/bash

if [[ -f /etc/letsencrypt/live/${DOMAIN}/fullchain.pem && -f /etc/letsencrypt/live/${DOMAIN}/privkey.pem ]]
  exit 0
fi

# wait for Nginx to come online
sleep 2

certbot certonly --non-interactive --agree-tos --email ${EMAIL} --webroot --webroot-path /var/www/letsencrypt --domains ${DOMAIN}

# add certs to nginx config
cat > /etc/nginx/extra/ssl.conf << EOF
listen 443 ssl http2;
server_name ${DOMAIN};
ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
EOF

# load new configuration
service nginx reload
